In [0]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
#Tensors

x = torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.rand(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.0026, 0.1895],
        [0.6989, 0.3479],
        [0.5932, 0.3153]])


In [3]:
x = torch.empty(3, 2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[2.6654e-35, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 6.1657e-44]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
torch.linspace(0, 1, steps=5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [5]:
x = torch.tensor([
                  [1,2],
                  [3,4],
                  [5,6]
])
x

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
#slicing

print(x.size())
print(x[:,1])
print(x[0,:])

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [8]:
y = x[1,1]
print(y)
print(y.item())

tensor(4)
4


In [9]:
# Reshape

print(x)
y = x.view(2,3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
x.view(6,)

tensor([1, 2, 3, 4, 5, 6])

In [11]:
x.view(6, -1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [12]:
# Simple tensor operations

x = torch.ones([3,2])
y = torch.ones([3,2])
z = x + y
print(x)
print(y)
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [13]:
z = y.add(x)
print(y)
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [14]:
z = y.add_(x) #updates y too
print(y)
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
